server:
  port: 5001
  servlet:
    contextPath: /configServer/
spring:
  application:
    name: spring-cloudd-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/darrenlsc/spring-cloud/
          search-paths: config-repo
          username: darrenlsc
          password: 0119cheng
